communities/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse

from .views import (
	communities_list,
	communities_create,
	communities_detail,
	communities_update,
	communities_delete,
	)


urlpatterns = [
	url(r'^$', communities_list, name='communities_list'),
	url(r'^create/$', communities_create, name='communities_create' ),
	url(r'^(?P<slug>[\w-]+)/$', communities_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', communities_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', communities_delete),

]

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from posts.views import *
from profiles.views import *
from signups.views import *

urlpatterns = [
  
    #url(r'^admin/', admin.site.urls),
    url(r'^$', 'signups.views.home', name='homepage'),
    url(r'^contact-us/$','signups.views.contactus', name='contactus'),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^communities/', include('communities.urls', namespace='communities')),
    url(r'^signups/$', 'signups.views.register', name='signup'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'signups.views.logout_page', name='logout'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
    url(r'^register/success/$', register_success),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^test/$', 'posts.views.post_profile', name='post_profile'),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import patterns, url

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	tags,
	#post_profile,
	user,
	PostLikeToggle,
	PostLikeAPIToggle,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
	url(r'^create/$', post_create, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like-toggle'),
	url(r'^api/(?P<slug>[\w-]+)/like/$', PostLikeAPIToggle.as_view(), name='like-api-toggle'),
	url(r'^(?P<slug>[\w-]+)/edit$', post_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
	url(r'^tag/(?P<tag>\w+)/$', tags),
	url(r'^$', user, name='list'),
	#url(r'^post_profile/$', post_profile, name='post_profile'),

	

    ]

communities/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
#from posts.models import Post


def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

#class CommunitiesManager(models.Manager):
#	def active(self, *args, **kwargs):
#		return super(CommunitiesManager, self).filter(community__slug=slug)



class CommunitiesManager(models.Manager):
    #def all(self):
     #   qs = super(CommunitiesManager, self).filter(parent=None)
      #  return qs

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommunitiesManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
        return qs


class Communities(models.Model):
    #community_id = models.BigIntegerField(primary_key=True)
    user = models.ForeignKey(User, null=True, blank=True)
    #posts = models.ForeignKey('posts.Post', on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True,
            blank=True,
            width_field="width_field",
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content_type   = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id      = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    parent         = models.ForeignKey("self", null=True, blank=True)

    def __unicode__(self):
        return self.name
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("communities:detail", kwargs={"slug": self.slug})



def create_slug(instance, new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = new_slug
    qs = Communities.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)



pre_save.connect(pre_save_post_receiver, sender=Communities)


  

communities/forms.py
from django import forms
from .models import Communities

class CommunitiesForm(forms.ModelForm):
	class Meta:
		model = Communities
		fields = [
			"name",
			"description",
			"image",
		]

communities/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse,HttpResponseRedirect, Http404
from .forms import CommunitiesForm
from .models import Communities
from posts.models import Post
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required


@login_required
def communities_create(request):
	form = CommunitiesForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user # User creates a Post
		instance.save()
		form.save_m2m()
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	else:
		messages.error(request, "Not Successfully Created")
	
	context = {
		"form": form,
	}
	return render(request, "communities/communities_form.html", context)


def communities_detail(request, slug=None):
	instance = get_object_or_404(Communities, slug=slug)
	queryset = Post.objects.filter(community__slug=slug)
	context = {
		"object_list": queryset,
		"instance": instance,
	}
	return render(request, "stories/post_list.html", context)


def communities_list(request):
	queryset = Communities.objects.all()
	query = request.GET.get("q")
	if query:
		queryset = queryset= queryset.filter(
				Q(name__icontains=query)|
				Q(description__icontains=query)
				).distinct()
	
	context = {
		"name": "List",
		"object_list": queryset
	}
	return render(request, "communities/communities_list.html", context)

@login_required
def communities_update(request, slug =None):
	#if not request.user.is_staff or not request.user.is_superuser:
	#	raise Http404
	instance = get_object_or_404(Communities, slug =slug)
	form = CommunitiesForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"title": instance.name,
		"instance":instance,
		"form":form,
	}

	return render(request, "communities/communities_form.html", context)

@login_required
def communities_delete(request, slug=None):
	#if not request.user.is_staff or not request.user.is_superuser:
	#	raise Http404
	instance = get_object_or_404(Communities, slug =slug)
	messages.success(request, "Successfully Deleted")
	instance.delete()
	return redirect("communities:communities_list")
	

templates/communities/communities_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="row">
	<div class='col-sm-12' style= "text-align:center">
		<h1>{{ instance.name }}</h1></br>
			<a class = "button" href='{% url "posts:create" %}'><button style= "margin-bottom: 50px"; "text-align:center" type="button" class="btn btn-primary communities-btn">Tell a story</button></br></a>
	</div>
</div>

<div class='col-sm-9 col-sm-offset-3'>	   		 	
	
    <form method='GET' action='' class='row' style= "text-align:center">
        <div class='col-sm-8'style= "text-align:center">
           <div class='input-group' style= "text-align:center">
                <input class='form-control' type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
                	<span class='input-group-btn'>
               			<button style="background-color:transparent"class='btn btn-default' type='submit'><i class="fa fa-search"></i></button>
                	</span>
            </div>
        </div>
	</form>
</div>


<div class='col-sm-6 col-sm-offset-3'>
	{% for obj in  object_list %}
		<div class="row">
			<div class="col-sm-12">
	    		<div class="thumbnail">
					<a href = '{{ obj.get_absolute_url}}'>{{ obj.title }}</a><br/>
						{% if obj.image %}
						<img class = "img-responsive" src = '{{ obj.image.url }}'>
						{% endif %}
						{% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
						{% if obj.user.get_full_name %}<p>Author:{{ obj.user.get_full_name }}</p>{% endif %}
						<p class='content-markdown'>{{ obj.content }}</p>
						{{ obj.content |linebreaks|truncatechars:120}}<br/>
						{{ obj.publish }}<br/>
						 {% if obj.tags %}<p>Labels:
	                        {% for tag in obj.tags.all %}
	                    <a href="/posts/tag/{{ tag }}">{{ tag.name }}</a>
	                    {% if not forloop.last %},{% endif%}
	                    {% endfor %}</p>{% endif %}
	                    <a class="button" href='{{ obj.get_absolute_url}}'>View</a>
				</div>
	   		</div>
	  	</div><hr/>
{% endfor %}
</div>
{% endblock content %}

templates/communities/communities_form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class='container'>
	   	<div class="col-sm-12" style= "text-align:center;">
			<h1>Create a community</h1></br>
				<form method = 'POST' action '' enctype='multipart/form-data' >{% csrf_token %}
				{{ form.as_p }}
					<input type = 'submit' value = 'Create Communities' />
				</form>
		</div>
	</div>
{% endblock content %}

templates/communities/communities_list.html
{% extends "base.html" %}
{% block content %}


<div class="row">
	<div class='col-sm-12' style= "text-align:center">
		<h1>Communities</h1></br>
			<a class = "button" href='{% url "communities:communities_create" %}'><button style= "margin-bottom: 50px"; "text-align:center" type="button" class="btn btn-primary communities-btn">Create a Community</button></br></a>
	</div>
</div>

<div class='col-sm-9 col-sm-offset-3'>
    <form method='GET' action='' class='row' style= "text-align:center">
        <div class='col-sm-8'style= "text-align:center">
           <div class='input-group' style= "text-align:center">
                <input class='form-control' type='text' name='q' placeholder='Search communities' value='{{ request.GET.q }}'/>
                	<span class='input-group-btn'>
               			<button style="background-color:transparent"class='btn btn-default' type='submit'><i class="fa fa-search"></i></button>
                	</span>
            </div>
        </div>
	</form>
</div>
	
<div class="row" style= "margin-left:50px; margin-right:50px; margin-top:100px;">   		 	
	{% for obj in  object_list %}
		<div class="col-sm-4" style="text-align:center">
			<div class="thumbnail">
				<a href = '{{ obj.get_absolute_url}}'><h2>{{ obj.name }}</h2></a></br>
				<p>{{ obj.description | truncatechars:20 }}</p> </br>
				{% if obj.image %}
					<img class = "img-responsive" src = '{{ obj.image.url }}'>
				{% endif %}
			</div>
		</div>
{% endfor %}
</div>

{% endblock content %}