communities/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse

from .views import (
	communities_list,
	communities_create,
	communities_detail,
	communities_update,
	communities_delete,
	)


urlpatterns = [
	url(r'^$', communities_list, name='communities_list'),
	url(r'^create/$', communities_create, name='communities_create' ),
	url(r'^(?P<slug>[\w-]+)/$', communities_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', communities_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', communities_delete),

]

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from posts.views import *
from profiles.views import *
from signups.views import *

urlpatterns = [
  
    #url(r'^admin/', admin.site.urls),
    url(r'^$', 'signups.views.home', name='homepage'),
    url(r'^contact-us/$','signups.views.contactus', name='contactus'),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^communities/', include('communities.urls', namespace='communities')),
    url(r'^signups/$', 'signups.views.register', name='signup'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'signups.views.logout_page', name='logout'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
    url(r'^register/success/$', register_success),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^test/$', 'posts.views.post_profile', name='post_profile'),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import patterns, url

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	tags,
	#post_profile,
	user,
	PostLikeToggle,
	PostLikeAPIToggle,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
	url(r'^create/$', post_create, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like-toggle'),
	url(r'^api/(?P<slug>[\w-]+)/like/$', PostLikeAPIToggle.as_view(), name='like-api-toggle'),
	url(r'^(?P<slug>[\w-]+)/edit$', post_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
	url(r'^tag/(?P<tag>\w+)/$', tags),
	url(r'^$', user, name='list'),
	#url(r'^post_profile/$', post_profile, name='post_profile'),

	

    ]

profiles/urls.py
from django.conf.urls import patterns, url

from .views import (
	profile_view,
	profile_update,
	#edit_info,
	#edit_jobs,
	#edit_qualifications,
	#edit_languages,
	#edit_pictures,
	#post_delete,
	
	)


urlpatterns = [
	
	url(r'^(?P<username>[\w.@+-]+)/$', profile_view, name='profile_view'),
	url(r'^(?P<username>[\w.@+-]+)/edit$', profile_update, name='profile_update'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_info, name='edit_info'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_jobs, name='edit_jobs'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_qualifications, name='edit_qualifications'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_languages, name='edit_languages'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_pictures, name='edit_pictures'),
	#url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    ]

posts/models.py
from __future__ import unicode_literals
from taggit.managers import TaggableManager
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify
from comments.models import Comment
from communities.models import Communities

from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    return "%s/%s" %(instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default =1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank = True, related_name='post_likes')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    community = models.ForeignKey(Communities, on_delete=models.CASCADE)
    language = models.CharField(max_length=120, blank = True)
    source = models.CharField(max_length=120, blank = True)
    summary = models.CharField(max_length=120,  blank = True)
    tags = TaggableManager(blank=True)


    def __unicode__(self):
            return self.name
    

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    # def get_api_url(self):
    #     return reverse("posts-api:detail", kwargs={"slug": self.slug})

    def get_like_url(self):
        return reverse("posts:like-toggle", kwargs={"slug": self.slug})

    def get_api_like_url(self):
        return reverse("posts:like-api-toggle", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]


    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def communities(self):
        instance = self
        qs = Communities.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type



def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)



pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget)
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
			"language",
			"source",
			"summary",
			"tags",
		]

profiles/forms.py
from django import forms
from .models import Profile



class ProfileForm(forms.ModelForm):
	
    class Meta:
        model = Profile
        fields =  [
            "location",
            "bio",
            "picture",   
		]


      

posts/views.py
from urllib import quote_plus
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
try:
    from django.utils import simplejson as json
except ImportError:
    import json
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.db.models import Q
from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from communities.models import Communities
from taggit.models import Tag
from django.views.decorators.http import require_POST
from django.views.generic import View
import datetime

from django.contrib.auth.models import User
from django.contrib.auth import get_user_model, authenticate
from django.views.generic import RedirectView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions


User = get_user_model()



@login_required
def post_create(request):
	#FORM
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		form.save_m2m()
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	else:
		messages.error(request, "Not Successfully Created")
	
	context = {
		"form": form,

	}
	return render(request, "stories/post_form.html", context)


@login_required
def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	share_string = quote_plus(instance.content)

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
	}
	#FORM SAVE
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()
	#COMMENTS
		new_comment, created = Comment.objects.get_or_create(
							user = request.user,
							content_type= content_type,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
						)

		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
	comments = instance.comments
	#COMMUNITIES

	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"comments": comments,
		"comment_form":form,
		"tags": tags,
	}

	extra_context={
            'objects':Post.objects.all(),
        } 

	return render(request, "stories/post_detail.html", context)


class PostLikeToggle(RedirectView):
	def get_redirect_url(self, *args, **kwargs):
		slug = self.kwargs.get("slug")
		print(slug)
		obj = get_object_or_404(Post, slug=slug)
		url_ = obj.get_absolute_url()
		user = self.request.user
		if user.is_authenticated():
			if user in obj.likes.all():
				obj.likes.remove(user)
			else:
				obj.likes.add(user)
		return url_


class PostLikeAPIToggle(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, slug=None, format=None):
        # slug = self.kwargs.get("slug")
        obj = get_object_or_404(Post, slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        updated = False
        liked = False
        if user.is_authenticated():
            if user in obj.likes.all():
                liked = False
                obj.likes.remove(user)
            else:
                liked = True
                obj.likes.add(user)
            updated = True
        data = {
            "updated": updated,
            "liked": liked
        }
        return Response(data)

def tags(request, tag):
	posts = Post.objects.filter(tags__name=tag)
	name = Post.objects.all(),
	context={
            'posts': posts,
            'tags':tag,
            'name': tag,
        } 
 
	return render(request, "stories/tags_list.html", context)


def post_list(request, slug=None):
	user = User.objects.all()
	today = timezone.now().date()
	queryset_list = Post.objects.active()#.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()
		queryset_list.user = request.user

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()

	context = {
		"object_list": queryset_list,
		"user": user,
		"title": "List",
		"today": today,
	}
	return render(request, "stories/post_list.html", context)

def user(request, username):
	user = User.objects.all()
	context = {
		"user": user,
	}
	return render(request, "stories/post_list.html", context)


@login_required
def post_update(request, slug=None):
	instance = get_object_or_404(Post, slug =slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		form.save_m2m()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())			

	context = {
		"title": instance.title,
		"instance":instance,
		"form":form,
		"tags":tags
	}

	return render(request, "stories/post_form.html", context)
	

def post_delete(request, slug=None):
	instance = get_object_or_404(Post, slug =slug)
	messages.success(request, "Successfully Deleted")
	instance.delete()
	return redirect("posts:list")

def post_profile(request):
	queryset_list = Post.objects.all()

	context = {
		"object_list": queryset_list,
	}

	return render(request, "profiles/profile_list.html", context)

profiles/views.py
from django.contrib import messages
from django.shortcuts import render, RequestContext, render_to_response, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import get_user_model
from django.forms.models import modelformset_factory
from profiles.models import Profile
from .forms import *
from signups import *
from posts.views import *
from posts.models import Post
from communities.models import Communities
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


User = get_user_model()


@login_required
def profile_view(request, username):
		user = get_object_or_404(User, username=username)
		userprofile = User.objects.get(username=username)
		profile, created = Profile.objects.get_or_create(user=user)
		#posts = Post.objects.filter(user=user)
		
		context = {
			'profile': profile, 
			'userprofile': userprofile,
			#'posts': posts
		}
		return render(request, 'profiles/profile_view.html', context)

@login_required
def profile_update(request, username):
		user = request.user.profile
		profile = Profile.objects.all()
		info = Profile.objects.get(user=request.user)
		
		if profile != request.user:
			return (request, 'profiles/profile_view.html')
		

		else:
			form = ProfileForm(request.POST or None, instance=info)
			if form.is_valid():
		 		instance=form.save(commit=False)
		 		instance.user = request.user
		 		instance.save()
		 		form.save_m2m()
		 		messages.success(request, "Successfully Created")
		 		return HttpResponseRedirect(instance.get_absolute_url())
		 	else:
		 		messages.error(request, "Not Successfully Created")
		 				
		 	context = {
		 		"form": form,
		 	}
		 	return render(request, 'profiles/profile_forms.html', context)

		

	

	

		

		








	

templates/contactus.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}

  <div class='row'>
		<div class='col-sm-6 col-sm-offset-3'>


		<h1 class='text-align-center'>{{ title }}</h1>
		

		<form method='POST' action='' enctype="multipart/form-data">{% csrf_token %}
		{{ form }}
		{{ email }}
		{{ message }}

		<input class='btn btn-default' type='submit' value='Submit' />

		</form>
	</div>
</div>
  
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


<div class ="container-fluid">
	{% for obj in  queryset_story %}
		<div class="col-md-6" style= "padding:0px;">
        	{% if obj.image %}
				<img class = "img-responsive" src = '{{ obj.image.url }}' >
			{% endif %}
		</div>
		<div class="col-md-6" style= "padding:0px;" >
			<div class = "featured-story">
				<h2><a href = '{{ obj.get_absolute_url}}'>{{ obj.title }}</a></h2><br/>
					{% if obj.user.get_full_name %}
						
						<p>by:<a href = '/profile/{{ obj.user }}'> {{ obj.user.get_full_name }} </p></a>
					{% endif %}		
					{% if obj.draft %}
						<h3>Staff only: Draft</h3>
					{% endif %}
					{% if obj.publish > today %}
						<h3>Staff Only: Future Post</h3>
					{% endif %}
					<p>{{ obj.content |truncatechars:300}}</p> <br/>
					<p><a href='{{ obj.get_absolute_url}}'>read more</a></p>
			</div>
		</div>	
	{% endfor %}
</div>

	<div class="container-fluid">
  		<div class="jumbotron" style= "margin: 0px">
    		<h1>Share your Heritage</h1> 
    			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> 
    			<a class = "button" href='{% url "posts:create" %}'><button type="button" class="btn btn-info jumbotron-btn">TELL YOUR STORY</button></a>
   		</div>
	</div>

	<div class="container-fluid">
  		<img style= "margin-top:0px; padding-top: 0px" class= "img-responsive" src="{% static 'css/images/roma.jpg' %}">
	</div>




	<div class = "container">

		<div class ="row">
			<div class="col-md-12">
				<div class="pull-center">
					<h1>Join your Community</h1>
				</div>
			</div>
		</div>


		<div class ="row">
			{% for obj in  queryset_community %}	
				<div class="col-md-4">
					<div class ="communities">
						<h1><a href = '{{ obj.get_absolute_url}}'>{{ obj.name }}</h1></a></br>
						{% if obj.image %}
						<img class = "img-circle" src = '{{ obj.image.url }}' alt="thumbnail"; >
						{% endif %}
						<p>{{ obj.description |truncatechars:50}}</p></br>
					</div>
				</div>
			{% endfor %}
		</div>
	

		<div class ="row" style= "text-align:center; margin-bottom: 50px;">
			<div class="col-md-12">
				<a class = "button" href='{% url "communities:communities_list" %}'><button type="button" class="btn btn-primary communities-btn">BROWSE COMMUNITIES</button></a>
			</div>
		</div>
	</div>

	<div class="container-fluid" style= "background-color: #5A81A6;">
		<div class="row" style= "padding:100px">
			<div class="col-md-6"><h1>About Heriga</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
			<div class="col-md-6">
				<img style= "margin:0px; padding: 0px" class= "img-responsive" src="{% static 'css/images/roma.jpg' %}">
			</div>
		</div>
	</div>

	<div class="container-fluid" style= "background-color: #5A81A6;" >
		<div class="row" style= "padding:100px"; "text-align:center">
			<div class="col-md-6" style= "margin-left:10px";>
				<img class= "img-responsive" src="{% static 'css/images/roma.jpg' %}">
			</div>
			
			<div class="col-md-6"><h1>Another About</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
		</div>
	</div>


	<footer class="footer">
		<div class="container-fluid">
			<div class="col-md-4">
				<h2><a class="" href='{% url "contactus" %}'>Contact us</a></h2></br>
				<P>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</P>
				<p>Email@aegis.com</p>
			</div>

			
			<div class="col-md-4">
				<div class = "social">
				  	<h2>Follow us</h2></br>
				  		<ul>
							<li><a href ="#"><i class="fa fa-facebook fa-3x"></i></a></li><br>
							<li><a href ="#"><i class="fa fa-twitter fa-3x"></i></a></li>
							<li><a href ="#"><i class="fa fa-google-plus fa-3x"></i>	</a></li>
						</ul><br>
				</div>
			</div>
				  			
			<div class="col-md-4">
				<h2>Subscribe</h2></br>
				  	<div class="input-group">
				      	<input type="text" class="form-control" placeholder="Email">
				      	<span class="input-group-btn">
				        	<button style= "background:transparent" class="btn btn-default" type="button">
				        		<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
				        	</button>
				      	</span>
				   	</div>
			</div>
		</div>
				 
			<div class= "container-fluid" style="background-color:#000000" "margin:0px;">
				<div class="row" style= "text-align:center">
				  	<div style= "color:#ffffff"; "font-size: 9px" class="col-md-12">
				  		<p>2016 © Heriga. All rights reserved<p>
				  	</div>
				</div>	
			</div>


	</footer>


{% endblock content %}

templates/js.html
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

templates/messages_display.html
 {% if messages %}
 <div class='container'>
 <div class="col-sm-12" style= "text-align:center">
    <div class='messages'>

    <ul class="messages" style= "text-decoration:none">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
</div>
{% endif %}

templates/post_form.html
{% extends "base.html" %}

{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}

{% block content %}
	<div class='container'>
	   	<div class="col-sm-12" style= "text-align:center;">
			<h1>Create a Story</h1></br>
			<form method = 'POST' action '' enctype='multipart/form-data' >{% csrf_token %}
				{{ form.as_p }}
				<input type = 'submit' value = 'Create Post' />
			</form>
		</div>
	</div>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% block content %}


<div class="row">
	<div class='col-sm-12' style= "text-align:center">
			{% for user in user.userpicture_set.all %}{% if user.image %}</br>
				<h1>This is {{ profile.user }} Profile</h1><img class= "img-responsive" src='{{ user.image.url }}'/></br>{% endif %}
			{% endfor %}
		<h1>Full Name</h1><p>{{ user.first_name }} {{ user.last_name }}</p></br>
		<h1>E-mail</h1><p>{{ user.email }}</p></br>
		<h1>Place of birth</h1><p>{{ profile.cityOfBirth }}, {{ profile.countryOfBirth}}, </p></br>
		<h1>Location</h1><p>{{ profile.cityofResidence }}, {{ profile.countryofResidence }}</p></br>
			<h1>Occupation</h1>{% for user in user.userjob_set.all %}
				<p>{{ user.occupation }}</p>{% endfor %}
			


	</div>
</div>
{% endblock content %}