mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from posts.views import *
from profiles.views import *
from signups.views import *

urlpatterns = [
  
    #url(r'^admin/', admin.site.urls),
    url(r'^$', 'signups.views.home', name='homepage'),
    url(r'^contact-us/$','signups.views.contactus', name='contactus'),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^communities/', include('communities.urls', namespace='communities')),
    url(r'^signups/$', 'signups.views.register', name='signup'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'signups.views.logout_page', name='logout'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
    url(r'^register/success/$', register_success),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^test/$', 'posts.views.post_profile', name='post_profile'),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import patterns, url

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	tags,
	#post_profile,
	user,
	PostLikeToggle,
	PostLikeAPIToggle,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
	url(r'^create/$', post_create, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like-toggle'),
	url(r'^api/(?P<slug>[\w-]+)/like/$', PostLikeAPIToggle.as_view(), name='like-api-toggle'),
	url(r'^(?P<slug>[\w-]+)/edit$', post_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
	url(r'^tag/(?P<tag>\w+)/$', tags),
	url(r'^$', user, name='list'),
	#url(r'^post_profile/$', post_profile, name='post_profile'),

	

    ]

profiles/urls.py
from django.conf.urls import patterns, url

from .views import (
	profile_view,
	profile_update,
	#edit_info,
	#edit_jobs,
	#edit_qualifications,
	#edit_languages,
	#edit_pictures,
	#post_delete,
	
	)


urlpatterns = [
	
	url(r'^(?P<username>[\w.@+-]+)/$', profile_view, name='profile_view'),
	url(r'^(?P<username>[\w.@+-]+)/edit$', profile_update, name='profile_update'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_info, name='edit_info'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_jobs, name='edit_jobs'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_qualifications, name='edit_qualifications'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_languages, name='edit_languages'),
	#url(r'^(?P<username>[\w.@+-]+)/edit$', edit_pictures, name='edit_pictures'),
	#url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    ]

communities/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
#from posts.models import Post


def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

#class CommunitiesManager(models.Manager):
#	def active(self, *args, **kwargs):
#		return super(CommunitiesManager, self).filter(community__slug=slug)



class CommunitiesManager(models.Manager):
    #def all(self):
     #   qs = super(CommunitiesManager, self).filter(parent=None)
      #  return qs

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommunitiesManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
        return qs


class Communities(models.Model):
    #community_id = models.BigIntegerField(primary_key=True)
    user = models.ForeignKey(User, null=True, blank=True)
    #posts = models.ForeignKey('posts.Post', on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True,
            blank=True,
            width_field="width_field",
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content_type   = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id      = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    parent         = models.ForeignKey("self", null=True, blank=True)

    def __unicode__(self):
        return self.name
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("communities:detail", kwargs={"slug": self.slug})



def create_slug(instance, new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = new_slug
    qs = Communities.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)



pre_save.connect(pre_save_post_receiver, sender=Communities)


  

posts/models.py
from __future__ import unicode_literals
from taggit.managers import TaggableManager
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify
from comments.models import Comment
from communities.models import Communities

from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    return "%s/%s" %(instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default =1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank = True, related_name='post_likes')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    community = models.ForeignKey(Communities, on_delete=models.CASCADE)
    language = models.CharField(max_length=120, blank = True)
    source = models.CharField(max_length=120, blank = True)
    summary = models.CharField(max_length=120,  blank = True)
    tags = TaggableManager(blank=True)


    def __unicode__(self):
            return self.name
    

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    # def get_api_url(self):
    #     return reverse("posts-api:detail", kwargs={"slug": self.slug})

    def get_like_url(self):
        return reverse("posts:like-toggle", kwargs={"slug": self.slug})

    def get_api_like_url(self):
        return reverse("posts:like-api-toggle", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]


    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def communities(self):
        instance = self
        qs = Communities.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type



def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)



pre_save.connect(pre_save_post_receiver, sender=Post)

profiles/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from posts.models import Post
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse




User = settings.AUTH_USER_MODEL


def upload_location(instance, filename):
	location = str(instance.user.username)
	return "%s/%s" %(location, filename)


class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, unique=True)
	location = models.CharField(max_length=50, null=True, blank=True)
	bio = models.TextField(max_length=500, blank=True)
	picture = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)

	def __unicode__(self):
		return self.user.username or ''

	def get_absolute_url(self):
		return reverse("profile:profile_view", args=[str(self.user)])


def post_save_user_model_receiver(sender,instance,created, *args, **kwargs):
	if created:
		try:
			Profile.objects.create(user=instance)
		except:
			pass
post_save.connect(post_save_user_model_receiver, sender=settings.AUTH_USER_MODEL)












# Job (Institution)
# Languages
	

#class UserJob (models.Model):
#	user = models.ForeignKey(User)
#	occupation = models.CharField(max_length=100, null=True, blank=True)
#	placeOfWork = models.CharField(max_length=100, null=True, blank=True)
#	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, null=True, blank=True)
#
#	def __unicode__(self, ):
#			return self.occupation or ''
#	
#
#class UserQualification (models.Model):
#	user = models.ForeignKey(User)
#	university = models.CharField(max_length=100, null=True, blank=True)
#	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, null=True, blank=True) 
#
#	def __unicode__(self, ):
#			return self.university or ''
#
#class UserLanguage (models.Model):
#	user = models.ForeignKey(User)
#	languages = models.CharField(max_length=50, null=True, blank=True)
#
#	def __unicode__(self, ):
#			return self.languages or ''	

profiles/forms.py
from django import forms
from .models import Profile



class ProfileForm(forms.ModelForm):
	
    class Meta:
        model = Profile
        fields =  [
            "location",
            "bio",
            "picture",   
		]


      

profiles/views.py
from django.contrib import messages
from django.shortcuts import render, RequestContext, render_to_response, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import get_user_model
from django.forms.models import modelformset_factory
from profiles.models import Profile
from .forms import *
from signups import *
from posts.views import *
from posts.models import Post
from communities.models import Communities
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


User = get_user_model()


@login_required
def profile_view(request, username):
		user = get_object_or_404(User, username=username)
		userprofile = User.objects.get(username=username)
		profile, created = Profile.objects.get_or_create(user=user)
		#posts = Post.objects.filter(user=user)
		
		context = {
			'profile': profile, 
			'userprofile': userprofile,
			#'posts': posts
		}
		return render(request, 'profiles/profile_view.html', context)

@login_required
def profile_update(request, username):
		user = request.user.profile
		profile = Profile.objects.all()
		info = Profile.objects.get(user=request.user)
		
		if profile != request.user:
			return (request, 'profiles/profile_view.html')
		

		else:
			form = ProfileForm(request.POST or None, instance=info)
			if form.is_valid():
		 		instance=form.save(commit=False)
		 		instance.user = request.user
		 		instance.save()
		 		form.save_m2m()
		 		messages.success(request, "Successfully Created")
		 		return HttpResponseRedirect(instance.get_absolute_url())
		 	else:
		 		messages.error(request, "Not Successfully Created")
		 				
		 	context = {
		 		"form": form,
		 	}
		 	return render(request, 'profiles/profile_forms.html', context)

		

	

	

		

		








	

templates/profiles/profile_detail.html
{% extends "base.html" %}
{% block content %}


<div class="row">
	<div class='col-sm-12' style= "text-align:center">
			{% for user in user.userpicture_set.all %}{% if profile.user.image %}</br>
				<h1>This is {{ profile.user }} Profile</h1><img class= "img-responsive" src='{{ user.image.url }}'/></br>{% endif %}
			{% endfor %}
			<h1>Full Name</h1>
				<p>{{ profile.user.first_name }} {{ profile.user.last_name }}</p></br>
			<h1>E-mail</h1><p>{{ profile.user.email }}</p></br>
			<h1>Place of birth</h1><p>{{ profile.cityOfBirth }}, {{ profile.countryOfBirth}}, </p></br>
		<h1>Location</h1><p>{{ profile.cityofResidence }}, {{ profile.countryofResidence }}</p></br>
			<h1>Occupation</h1>{% for item in profile.user.userjob_set.all %}
				<p>{{ item.occupation }}</p>{% endfor %}

	</div>
</div>
	



<!--POSTS_PROFILE-->

<div class='col-sm-6 col-sm-offset-3'>
	{% for obj in profile.user.post_set.all %}
			<div class="row">
				<div class="col-sm-12">
	    			<div class="thumbnail">
	    				<a href = '{{ obj.get_absolute_url}}'>{{ obj.title }}</a><br/>
							{% if obj.image %}
								<img class = "img-responsive" src = '{{ obj.image.url }}'>
							{% endif %}

						<!--Draft-->
						{% if obj.draft %}
							<h3>Staff only: Draft</h3>
						{% endif %} 

						{% if obj.publish > today %}
							<h3>Staff Only: Future Post</h3>
						{% endif %}

						<!--USER-->
						{{ user.request }}
						{% if obj.user.get_full_name %}
							by:<a href = '/profile/{{ obj.user }}'>{{ obj.user.get_full_name }}</a>
						{% endif %}
						
						<p class='content-markdown'>{{ obj.content }}</p>
						{{ obj.content |linebreaks|truncatechars:120}}<br/>
						{{ obj.publish }}<br/>
						 {% if obj.tags %}<p>Labels:
	                        {% for tag in obj.tags.all %}
	                    <a href="/posts/tag/{{ tag }}">{{ tag.name }}</a>
	                    {% if not forloop.last %},{% endif%}
	                    {% endfor %}</p>{% endif %}
	                    <a class="button" href='{{ obj.get_absolute_url}}'>View</a>
	              	
	           	</div>
	      	</div>
	
</div>
{% endfor %}


<!--COMMUNITIES-->

<div class="row" style= "margin-left:50px; margin-right:50px; margin-top:100px;">   		 	
	{% for obj in  profile.user.communities_set.all %}
		<div class="col-sm-4" style="text-align:center">
			<div class="thumbnail">
				<a href = '{{ obj.get_absolute_url}}'><h2>{{ obj.name }}</h2></a></br>
				<p>{{ obj.description | truncatechars:20 }}</p> </br>
				{% if obj.image %}
					<img class = "img-responsive" src = '{{ obj.image.url }}'>
				{% endif %}
			</div>
		</div>
{% endfor %}
</div>

{% endblock content %}

templates/profiles/profile_forms.html
{% extends "base.html" %}
{%  block jquery %}

	$('#myTab a').click(function (e) {
	  e.preventDefault()
	  $(this).tab('show')
	})
	{% endblock %}


{% block content %}
	<div class='container'>
	   	<div class="col-sm-12" style= "text-align:center;">
	   		<h1>Edit your Profile</h1></br>

	   		<ul class="nav nav-tabs" id="myTab">
				<li class="active">
					<a class="active" href="#home" role="tab">Information</a>
				</li>
				<!--
				<li>
					<a href="#jobs" role="tab">Jobs</a>
				</li>
				<li>
					<a href="#qualifications" role="tab">Qualifications</a>
				</li>
				<li>
					<a href="#languages" role="tab">Languages</a>
				</li>
				<li>
					<a href="#pictures" role="tab">Pictures</a>
				</li>-->
			</ul>

					<!-- Tab panes -->
			<div class="tab-content">
				<div class="tab-pane active" id="home"> 
					<form method = 'POST' action '' enctype='multipart/form-data' >{% csrf_token %}
						<div class = "row">
							<p>Edit General Info</p>
								{{ user.request }}
								{{ form.as_p }}
								
						</div>
						<input type = 'submit' value = 'Update' />
					</form>
				</div>
				
				<div class="tab-pane" id="jobs">
					<form method = 'POST' action '' enctype='multipart/form-data' >{% csrf_token %}
						{{ formset_j.as_p }}
				</div>
				
				</form>

				<div class="tab-pane" id="qualifications">
					<form method = 'POST' action '' enctype='multipart/form-data' >{% csrf_token %}
						{{ formset_q.as_p }}
				</div>
					
				<div class="tab-pane" id="languages">
					<form method = 'POST' action '' enctype='multipart/form-data' >{% csrf_token %}
						{{ formset_l.as_p. }}
				</div>
				<!--<div class="tab-pane" id="pictures">
					<form method = 'POST' action '' enctype='multipart/form-data' >{% csrf_token %}
						{{ formset_p.as_a }}
				</div>-->
			</div>
		</div>
	</div>
{% endblock content %}

templates/profiles/profile_list.html
{% extends "base.html" %}
{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
{% for obj in  object_list %}
	<div class="row">
		<div class="col-sm-12">
    		<div class="thumbnail">
				<a href = '{{ obj.get_absolute_url}}'>{{ obj.title }}</a><br/>
					{% if obj.image %}
					<img class = "img-responsive" src = '{{ obj.image.url }}'>
					{% endif %}
					{% if obj.draft %}
						<h3>Staff only: Draft</h3>
					{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
					<!--USER-->
					
						
					{% if obj.user.get_full_name %}
						by:<a href = '/profile/{{ user }}'>{{ obj.user.get_full_name }}</a>
					}
					}
					{% endif %}
					
{% for item in user %}
{{ item.username }}

{% endfor %}



					<p class='content-markdown'>{{ obj.content }}</p>
					{{ obj.content |linebreaks|truncatechars:120}}<br/>
					{{ obj.publish }}<br/>
					 {% if obj.tags %}<p>Labels:
                        {% for tag in obj.tags.all %}
                    <a href="/posts/tag/{{ tag }}">{{ tag.name }}</a>
                    {% if not forloop.last %},{% endif%}
                    {% endfor %}</p>{% endif %}
                    <a class="button" href='{{ obj.get_absolute_url}}'>View</a>



  	</div><hr/>

{% endfor %}




{% endblock content %}

templates/profiles/profile_view.html
{% extends "base.html" %}
{% block content %}


<div class="row">
	<div class='col-sm-12' style= "text-align:center">
		
			
			{{ profile.user }}2

			{{ profile.location}}3
			
			{{ profile.info }}5
		

	</div>
</div>
	



<!--POSTS_PROFILE-->

<!--FIX-->

<div class='col-sm-6 col-sm-offset-3'>
	{% for obj in profile.user.post_set.all %}
			<div class="row">
				<div class="col-sm-12">
	    			<div class="thumbnail">
	    				<a href = '{{ obj.get_absolute_url}}'>{{ obj.title }}</a><br/>
							{% if obj.image %}
								<img class = "img-responsive" src = '{{ obj.image.url }}'>
							{% endif %}

						
						<!--USER-->
						{{ user.request }}
						{% if obj.user.get_full_name %}
							by:<a href = '/profile/{{ obj.user }}'>{{ obj.user.get_full_name }}</a>
						{% endif %}
						
						<p class='content-markdown'>{{ obj.content |linebreaks|truncatechars:120}}<br/></p>
						
						{{ obj.publish }}<br/>
						 {% if obj.tags %}<p>
	                        {% for tag in obj.tags.all %}
	                    <a href="/posts/tag/{{ tag }}">{{ tag.name }}</a>
	                    {% if not forloop.last %},{% endif%}
	                    {% endfor %}</p>{% endif %}
	                    <a class="button" href='{{ obj.get_absolute_url}}'>View</a>
	              	
	           	</div>
	      	</div>
	
</div>
{% endfor %}


<!--COMMUNITIES-->

<div class="row" style= "margin-left:50px; margin-right:50px; margin-top:100px;">   		 	
	{% for obj in  profile.user.communities_set.all %}
		<div class="col-sm-4" style="text-align:center">
			<div class="thumbnail">
				<a href = '{{ obj.get_absolute_url}}'><h2>{{ obj.name }}</h2></a></br>
				<p>{{ obj.description | truncatechars:20 }}</p> </br>
				{% if obj.image %}
					<img class = "img-responsive" src = '{{ obj.image.url }}'>
				{% endif %}
			</div>
		</div>
{% endfor %}
</div>

{% endblock content %}